on:
  push:
    branches:
      - develop
    paths:
      - 'packages/Entry-Auth/**'

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: stag
          access_key: ${{ secrets.ENTRY_AUTH_ACCESS_KEY }}
          base_url: packages/Entry-Auth
          config_file_path: packages/Entry-Auth/.xquare/config.yaml
          buildargs: |
            BRANCH=develop
            VITE_MAIN_URL=${{ secrets.STAG_VITE_MAIN_URL }}
            VITE_AUTH_URL=${{ secrets.STAG_VITE_AUTH_URL }}
            VITE_APPLY_URL=${{ secrets.STAG_VITE_APPLY_URL }}
            VITE_ADMIN_URL=${{ secrets.STAG_VITE_ADMIN_URL }}
            VITE_SERVER_URL=${{ secrets.STAG_VITE_SERVER_URL }}
